info:
  contact: {}
  license: {}
paths:
  /api/v1/tags:
    get: {}
    post: {}
  /api/v1/tags/{id}:
    delete:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: Delete article tag
    put: {}
swagger: "2.0"
